### PR TITLE
#4 - login screen

### PR DESCRIPTION
**Pull request by BarTracz**
Until the API is released for use, it will remain as it is(I hope).

### CODE REVIEW

**Review by EwelinaSkrzypacz — COMMENTED** [review]
I don't know how to run this project on Linux. After running command from readme `javafx:run` I see error:

`javafx:run: command not found`

Please add more details to readme, step-by-step how to run this app.

**Comment by BarTracz** [comment]
Readme has better instructions now.

**Review by EwelinaSkrzypacz — COMMENTED** [review]
1. For me it works now - at least I can see something

image


But I fill bad e-mail and I wanted to login with good credentials and I can't - after click "Login" I still see information that "Wrong email or password"

And btw. please use `example` domain in email address.

2. Design will be improved somehow or this is the final concept?
3. Title of application is "Hello!" - can we call it "E-motion" or something like that?
4. Please next time add some screenshots to pr - not all people that make cr will run the app and thanks to screenshot they will know how app looks

**Comment by BarTracz** [comment]
Now everything should be fine. When it comes to design, I'm currently waiting for the logo, when I receive it, I will be able to adapt the entire window design to the style of the logo.

**Review by EwelinaSkrzypacz — APPROVED** [review]

**Review by zmigrOO — APPROVED** [review]

**Pull request merged**
