### PR TITLE
#9 - admin dashboard

### LINKED ISSUE #9: Admin dashboard
There is a need to create certain tabs in admin dashboard:

- [x] Import section to run imports and check history of imports
- [x] CRUD for providers
- [x] CRUD for cities
- [x] CRUD for countries
- [ ] CRUD for opinions
- [ ] CRUD for users

If there won't be any main page, maybe we should add tab "map" with pins, as checkpoint that points are placed correctly?

### PR DESCRIPTION
**Pull request by BarTracz**
This should close #9 . I will add tests and finish map in another pull request.

### CODE REVIEW

**Review by EwelinaSkrzypacz — COMMENTED** [review]
1. Can we add some highlighting or something on navigation, when user is on some page? I mean now I don't know at first glance of eye where I am (I know that on the top of the window with application there is a title, but it's not noticable.

image

2. Search on all indexes doesn't work, even I wrote phrase that is in the table I see information `No content in table`.

3. Validation errors should be displayed in red - now they are in black, not noticeable

image


4. Providers CRUD - how I can add file?

image

5. I don't like this idea of ​​"Edit & Delete" on one screen - it's better to add icons with editing/deleting next to the table with resources (like countries)

6. I'm not a big fan of this design

**Comment by BarTracz** [comment]
1. There is now a dropShadow for the chosen tab.
2. Now, search searches are in every column instead of just names.
3. Errors are now red, and successes are green.
4. API does not support file uploads, so it is what it is for now.
5. I don't know if it is possible to do this that way for JavaFX tables.
6. I would like to redesign everything but time does not allow me to.

**Review by EwelinaSkrzypacz — COMMENTED** [review]
-  Cities CRUD:

image

1. Why I see city with fields NaN? And also something wrong is with name - there is question mark in it
2. In field "Country" user have to write country id, not country name - please chanage label to Country ID or smth like that
3. When I provide in the form the country id that does not exist I see error "Error while saving the city" - this message is too general for me
4. On my laptop full HD I don't see search


- Country CRUD

image

1. I believe here it should be label "ISO" not "Country"
2. On my laptop full HD I don't see search

- Can we make at least on buttons hover effect like ` cursor: pointer;`?

**Comment by BarTracz** [comment]
1. It is because some scrappers are not working properly. It is being fixed.
2. Changed.
3. The API does not return informative errors; for bad ID, it returns 200 with an OK, so I made this that way.
4. Now it should show.

1. Changed
2. Now it should show.

**Review by EwelinaSkrzypacz — COMMENTED** [review]
For me search works only if I provide city id or country id. Is it okay for us?

**Comment by BarTracz** [comment]
image

**Review by EwelinaSkrzypacz — APPROVED** [review]
After completely restart API, it works, so :+1:

**Review by JakubKermes — APPROVED** [review]

**Pull request merged**
